/**
 * This file was generated by Convex dev.
 *
 * This file is required to make type generation work.
 * It provides types for all functions in `convex/`.
 *
 * You should not edit this file manually.
 */

import type {
  FunctionReference,
  FunctionArgs,
  FunctionReturnType,
  DataModelFromSchemaDefinition,
} from "convex/server";
import type { GenericActionCtx } from "convex/server";

export const api = {} as any;

// Workspaces
api.workspaces = {
  list: {} as FunctionReference<"query", "public", {}, DataModelFromSchemaDefinition<{
    workspaces: {
      title: string;
      model: string;
    };
    messages: {
      workspaceId: any;
      role: string;
      content: string;
      model?: string;
    };
  }>[]>,
  get: {} as FunctionReference<"query", "public", { workspaceId: any }, DataModelFromSchemaDefinition<{
    workspaces: {
      title: string;
      model: string;
    };
    messages: {
      workspaceId: any;
      role: string;
      content: string;
      model?: string;
    };
  }> | null>,
  create: {} as FunctionReference<"mutation", "public", {
    title: string;
    model: string;
  }, any>,
  update: {} as FunctionReference<"mutation", "public", {
    workspaceId: any;
    title: string;
  }, void>,
  remove: {} as FunctionReference<"mutation", "public", { workspaceId: any }, void>,
};

// Messages
api.messages = {
  list: {} as FunctionReference<"query", "public", { workspaceId: any }, DataModelFromSchemaDefinition<{
    workspaces: {
      title: string;
      model: string;
    };
    messages: {
      workspaceId: any;
      role: string;
      content: string;
      model?: string;
    };
  }>[]>,
  add: {} as FunctionReference<"mutation", "public", {
    workspaceId: any;
    role: string;
    content: string;
    model?: string;
  }, any>,
  remove: {} as FunctionReference<"mutation", "public", { messageId: any }, void>,
};

// Search
api.search = {
  search: {} as FunctionReference<"action", "public", { query: string }, {
    results: Array<{
      title: string;
      url: string;
      snippet: string;
    }>;
  }>,
};

export default api;