/**
 * Generated data model for the Convex backend.
 *
 * THIS FILE IS GENERATED BY CONVEX DEV AND SHOULD NOT BE EDITED.
 *
 * Generated at: 2024-01-01T00:00:00.000Z
 */

export type TableNames = "workspaces" | "messages";

export type DataModel = {
  workspaces: {
    _id: any;
    _creationTime: number;
    title: string;
    model: string;
  };
  messages: {
    _id: any;
    _creationTime: number;
    workspaceId: any;
    role: string;
    content: string;
    model?: string;
  };
};