/**
 * Generated utilities for implementing Convex server functions.
 *
 * THIS FILE IS GENERATED BY CONVEX DEV AND SHOULD NOT BE EDITED.
 *
 * Generated at: 2024-01-01T00:00:00.000Z
 */

import type { DataModel } from "./dataModel";
import type {
  ActionBuilder,
  MutationBuilder,
  QueryBuilder,
} from "convex/server";

export type GenericActionCtx = ActionCtx<DataModel>;
export type GenericMutationCtx = MutationCtx<DataModel>;
export type GenericQueryCtx = QueryCtx<DataModel>;

export type ActionCtx<DM extends DataModel> = {
  db: DatabaseReader<DM>;
  auth: Auth;
  scheduler: Scheduler<DM>;
  storage: Storage;
  runMutation: <Args extends any[], Return>(
    mutation: MutationBuilder<DM, Args, Return>,
    ...args: Args
  ) => Promise<Return>;
  runQuery: <Args extends any[], Return>(
    query: QueryBuilder<DM, Args, Return>,
    ...args: Args
  ) => Promise<Return>;
  runAction: <Args extends any[], Return>(
    action: ActionBuilder<DM, Args, Return>,
    ...args: Args
  ) => Promise<Return>;
};

export type MutationCtx<DM extends DataModel> = {
  db: DatabaseWriter<DM>;
  auth: Auth;
  scheduler: Scheduler<DM>;
  storage: Storage;
  runQuery: <Args extends any[], Return>(
    query: QueryBuilder<DM, Args, Return>,
    ...args: Args
  ) => Promise<Return>;
};

export type QueryCtx<DM extends DataModel> = {
  db: DatabaseReader<DM>;
  auth: Auth;
  storage: Storage;
};

export type QueryBuilder<DM extends DataModel, Args extends any[], Return> = (
  ctx: GenericQueryCtx,
  ...args: Args
) => Promise<Return>;

export type MutationBuilder<DM extends DataModel, Args extends any[], Return> = (
  ctx: GenericMutationCtx,
  ...args: Args
) => Promise<Return>;

export type ActionBuilder<DM extends DataModel, Args extends any[], Return> = (
  ctx: GenericActionCtx,
  ...args: Args
) => Promise<Return>;

import {
  query as queryImpl,
  mutation as mutationImpl,
  action as actionImpl,
} from "convex/server";

export const query = <Args extends any[], Return>(
  func: QueryBuilder<DataModel, Args, Return>
) => queryImpl(func);

export const mutation = <Args extends any[], Return>(
  func: MutationBuilder<DataModel, Args, Return>
) => mutationImpl(func);

export const action = <Args extends any[], Return>(
  func: ActionBuilder<DataModel, Args, Return>
) => actionImpl(func);

// Re-export types from convex/server
export type {
  Auth,
  DatabaseReader,
  DatabaseWriter,
  Scheduler,
  Storage,
  VectorSearch,
  VectorIndex,
  GenericValidator,
  TableNamesInDataModel,
  DocumentByName,
  IndexedData,
  IndexNames,
  IndexRange,
  PaginationOptions,
  PaginationResult,
  PaginationResultBuilder,
  FilterBuilder,
  OrderBuilder,
  SearchFilter,
  SearchFilterBuilder,
  FullDocument,
  SystemTableNames,
  TableNames,
  DataModelFromSchemaDefinition,
  Document,
  Doc,
  TableInfo,
  Indexes,
  IndexesBuilder,
  Validator,
  VArray,
  VBoolean,
  VId,
  VLiteral,
  VNull,
  VNumber,
  VObject,
  VOptional,
  VRecord,
  VString,
  VUnion,
  Value,
  Infer,
  ObjectTypeFrom,
} from "convex/server";

import { v } from "convex/values";
export { v };